name: Build

on:
  push:
    branches: [develop, release]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'CI SKIP')"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'yarn'
      - if: github.ref == 'refs/heads/develop'

      - name: Caching yarn dependencies
        run: yarn install
        
      - name: Build
        run: yarn build

      - if: github.ref == 'refs/heads/develop'
        name: Deploy @develop
        run: |
          mkdir -p gh-pages && cd gh-pages
          git init
          git remote add secure-origin https://${{ secrets.GH_TOKEN }}@github.com/postory-app/postory.app.git
          git pull secure-origin master
          rm -rf develop
          cp -rf ../dist develop
          git config user.name  "CI Robot"
          git config user.email "justintwd+robot@gmail.com"
          git add .
          git commit -m "chore(ci): update assets" --amend
          git push --force secure-origin master
      - if: github.ref == 'refs/heads/develop'
        name: Slack Notification @develop
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: notify-app-develop-build
          SLACK_COLOR: 'good'
          SLACK_ICON: https://gravatar.com/avatar/f6b82105390335f2ba06f6eeb54d1d8f?s=48&d=robohash&r=x
          SLACK_MESSAGE: |

            :chrome: <https://postory.app/develop|查看官網 開發版>

            :request-changes: <https://github.com/postory-app/landing-page/commits/develop|更新日誌 (需登入 Github)>
          SLACK_TITLE: POSTORY 官網 更新通知
          SLACK_USERNAME: CI Robot
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_DEV }}
          MSG_MINIMAL: true
          SLACK_FOOTER: '由於採用 cdn 技術，網站內容至多需要發布 10 分鐘後才會完全更新'
